server:
  port: 18000
spring:
  redis:
    host: 192.168.56.10
    port: 6379
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719
  session:
    store-type: redis
#  task:
#    scheduling:
#      pool:
#        size: 5